import { Metadata } from 'next'
import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from 'next/font/google'
import {MarketplaceProvider} from '../../contexts/Marketplace'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NFT Marketplace',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <MarketplaceProvider>
          {children}
      </MarketplaceProvider>
    </body>
    </html>
  )
}
